### ISSUE TITLE
Generate mazes in VizDoom

### ISSUE THREAD

**Issue by WangChen100** [alex-petrenko/curious-rl#2]
Hi alex, thank you very much for your help before.

I have another question. When I generate the wad file for building maze by myself, how can I set the initialized location and the goal location?

In other words, do your know how to generate maze_sparse.wad and maze_very_sparse.wad? It seems that we can build the wad file of mazes by omgifol module. But unfortunately I don't know how to set agent's original location and goal.

Could you offer some clues? Thanks.

**Comment by alex-petrenko** [comment]
Hi, @WangChen100 !
I used a tool called Slade that allows you to modify .wad files, including the agent position and anything else you can imagine.
Not sure about omgifol.

**Comment by WangChen100** [comment]
Thank you very very much!
